name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set lowercase owner name
      run: |
        echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ForDocker/  # Указываем папку с Dockerfile
        file: ForDocker/Dockerfile  # Явно указываем путь
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:latest
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:${{ github.sha }}
