name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g semantic-release
        npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

  docker:
    name: Build and Push Docker
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Get release version
      id: version
      run: |
        if [ -f "release-version.txt" ]; then
          VERSION=$(cat release-version.txt)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        else
          echo "version=latest" >> $GITHUB_OUTPUT
        fi

    - name: Set lowercase repository names
      run: |
        echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "REPO_LC=${GITHUB_REPOSITORY#*/,,}" >> $GITHUB_ENV

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ForDocker/
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:latest
          ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ github.sha }}
          ghcr.io/${{ env.OWNER_LC }}/${{ env.REPO_LC }}:${{ steps.version.outputs.version }}
