name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write  # Необходимо для доступа к GitHub OIDC
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify Dockerfile exists
      run: |
        ls -la ForDocker/
        if [ ! -f "ForDocker/Dockerfile" ]; then
          echo "Error: Dockerfile not found in ForDocker/"
          exit 1
        fi
    
    - name: Set lowercase owner
      run: |
        echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  # Теперь будет работать с permissions
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ForDocker/
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:latest
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:${{ github.sha }}
