name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify Dockerfile exists
      run: |
        ls -la ForDocker/
        if [ ! -f "ForDocker/Dockerfile" ]; then
          echo "Dockerfile not found in ForDocker directory!"
          exit 1
        fi
    
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set lowercase owner name
      run: |
        echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:latest
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:${{ github.sha }}
