name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g semantic-release
        npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

  docker:
    name: Build image & push
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify Dockerfile exists
      run: |
        ls -la ForDocker/
        if [ ! -f "ForDocker/Dockerfile" ]; then
          echo "Error: Dockerfile not found in ForDocker/"
          exit 1
        fi
    
    - name: Set lowercase owner and repo
      run: |
        echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "REPO_LC=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "REPO_LC=${REPO_LC,,}" >> $GITHUB_ENV
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get release version
      id: version
      run: |
        # Get the latest release tag
        VERSION=$(git describe --tags --abbrev=0)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ForDocker/
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:latest
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:${{ github.sha }}
          ghcr.io/${{ env.OWNER_LC }}/simpleapp:${{ steps.version.outputs.version }}
